const data = {
    // About Page
    about: {
        pageName: "About Us",
        pageIntro1: `Who are we? Opmantek is a team `,
        pageIntro2: `of talented individuals working together to`,
        pageIntro3: `make software people love.`,
        aboutText1: "We develop multi-award winning",
        aboutText2: "enterprise-className software that helps IT",
        aboutText3: "teams audit IT environments.",
        bookBtn: "Book a Demo",
        contactBtn: "Contact Us",
        location: "Location",
        locationList1: [
            {   class: "location",
                imglink: "./aboutus-images/locations/location-1.svg",
                locationTitle: "Head Office and USA West Coast",
                callimglink: "./aboutus-images/call.svg",
                phoneNumber: "+1 (415) 322 2479",
                msgLink: "./aboutus-images/message.svg",
                email: "contact@opmantek.com",      
                addressLink: "./aboutus-images/location.svg",
                address: `One Harbor Drive, Suite 300, Sausalito, CA, 94965 United
                States of America`,
            },
            {   class: "location",
                imglink: "./aboutus-images/locations/location-2.svg",
                locationTitle: "Head Office and USA West Coast",
                callimglink: "./aboutus-images/call.svg",
                phoneNumber: "+1 (415) 322 2479",
                msgLink: "./aboutus-images/message.svg",
                email: "contact@opmantek.com",      
                addressLink: "./aboutus-images/location.svg",
                address: `One Harbor Drive, Suite 300, Sausalito, CA, 94965 United
                States of America`,
            },
            {   class: "location",
                imglink: "./aboutus-images/locations/location-3.svg",
                locationTitle: "Head Office and USA West Coast",
                callimglink: "./aboutus-images/call.svg",
                phoneNumber: "+1 (415) 322 2479",
                msgLink: "./aboutus-images/message.svg",
                email: "contact@opmantek.com",      
                addressLink: "./aboutus-images/location.svg",
                address: `One Harbor Drive, Suite 300, Sausalito, CA, 94965 United
                States of America`,
            },
            {   class: "location",
            imglink: "./aboutus-images/locations/location-4.svg",
            locationTitle: "Head Office and USA West Coast",
            callimglink: "./aboutus-images/call.svg",
            phoneNumber: "+1 (415) 322 2479",
            msgLink: "./aboutus-images/message.svg",
            email: "contact@opmantek.com",      
            addressLink: "./aboutus-images/location.svg",
            address: `One Harbor Drive, Suite 300, Sausalito, CA, 94965 United
            States of America`,
        },
        {   class: "location",
            imglink: "./aboutus-images/locations/location-5.svg",
            locationTitle: "Head Office and USA West Coast",
            callimglink: "./aboutus-images/call.svg",
            phoneNumber: "+1 (415) 322 2479",
            msgLink: "./aboutus-images/message.svg",
            email: "contact@opmantek.com",      
            addressLink: "./aboutus-images/location.svg",
            address: `One Harbor Drive, Suite 300, Sausalito, CA, 94965 United
            States of America`,
        },
        {   class: "location",
            imglink: "./aboutus-images/locations/location-6.svg",
            locationTitle: "Head Office and USA West Coast",
            callimglink: "./aboutus-images/call.svg",
            phoneNumber: "+1 (415) 322 2479",
            msgLink: "./aboutus-images/message.svg",
            email: "contact@opmantek.com",      
            addressLink: "./aboutus-images/location.svg",
            address: `One Harbor Drive, Suite 300, Sausalito, CA, 94965 United
            States of America`,
        },
        ],
        productFeatureTitle: "Why Top Companies use NMIS 9",
        product1: [
            {className: "products",imgLink: "./product-images/product-feature/car-engine1.svg",buisnessText:"Sophisticated Business Rules", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
            {className: "products",imgLink: "./product-images/product-feature/think-out-of-the-box1.svg",buisnessText:"Pre-Configured Out-of-the-", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
            {className: "products",imgLink: "./product-images/product-feature/maximize1.svg",buisnessText:"Massively Scalable", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
            {className: "products",imgLink: "./product-images/product-feature/visibility1.svg",buisnessText:"Visible Operational Impact", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
            {className: "products",imgLink: "./product-images/product-feature/heart-monitoring1.svg",buisnessText:"Automated Health Live", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
            {className: "products",imgLink: "./product-images/product-feature/setting1.svg",buisnessText:"Customizable Alert Escalation", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
        ],
        companyListIntro: "Trusted By over 150,000 Companies including:",
        companyList1 : [
            {imgLink: "./product-images/companies/bloomberg.svg",imgName: "bloomberg"},
            {imgLink: "./product-images/companies/standford.svg",imgName: "stanford"},
            {imgLink: "./product-images/companies/cambridge.svg",imgName: "cambridge"},
            {imgLink: "./product-images/companies/microsoft.svg",imgName: "microsoft"},
            {imgLink: "./product-images/companies/ETh.svg",imgName: "Eth"},
            {imgLink: "./product-images/companies/stitch.svg",imgName: "stitch"},
            {imgLink: "./product-images/companies/google.svg",imgName: "google"},
            {imgLink: "./product-images/companies/opengv.svg",imgName: "opengv"},
            {imgLink: "./product-images/companies/allgero.svg",imgName: "allgero"},
            {imgLink: "./product-images/companies/amazone.svg",imgName: "amazone"},
            {imgLink: "./product-images/companies/circleup.svg",imgName: "circleup"},
            {imgLink: "./product-images/companies/yellowlogo.svg",imgName: "yellowlogo"},
        ],
        storyTitle: "Our story",
        storyparagraph1: "Our FirstWave support engineers are highly skilled",
        storyparagraph2: "and experienced in NMIS, Open-AudIT and all of our",
        storyparagraph3: "commercial products and helped customers from",
        storyparagraph4: "We work closely with you during implementation",
        storyparagraph5: "We work closely with you during implementation",
        storyparagraph6: "and rollout, as well as post delivery of our solutions.",
        storyparagraph7: "as well as post delivery of our solutions.",
        ourStoryText1: `Our FirstWave support engineers are highly skilled and experienced
        in NMIS, Open-AudIT and all of our commercial products and helped
        customers from Telcos, MSP, enterprise organisations.Our FirstWave
        support engineers are highly skilled and experienced in NMIS,
        Open-AudIT and all of our commercial products and helped customers
        from Telcos, MSP, enterprise organisations..`,
        ourStoryText2: `Our FirstWave support engineers are highly skilled and experienced
        in NMIS, Open-AudIT and all of our commercial products and helped
        customers from Telcos, MSP, enterprise organisations.`,
        ourStoryText3: `Our FirstWave support engineers are highly skilled and experienced
        in NMIS, Open-AudIT and all of our commercial products and helped
        customers from Telcos, MSP, enterprise organisations.Our FirstWave
        support engineers are highly skilled and experienced in NMIS,
        Open-AudIT and all of our commercial products and helped customers
        from Telcos, MSP, enterprise organisations.Our FirstWave support
        engineers are highly skilled and experienced in NMIS, Open-AudIT and
        all of our commercial products and helped customers from Telcos,
        MSP, enterprise organisations.`,
        ourStoryText4: `Our FirstWave support engineers are highly skilled and experienced
        in NMIS, Open-AudIT and all of our commercial products and helped
        customers from Telcos, MSP, enterprise organisations.`,
        ourStoryText5: `We’re tired with recruiting and we know it can be done better. We’re
        starting with juniors and tech.`,
        ourTeamTitle: "Meet Our Team Leaders",
        teamsList1 : [
            {class: "member",imgLink: "./aboutus-images/our-team/member-1.svg",name: "Michal Kosinski",post: "General Manager"},
            {class: "member",imgLink: "./aboutus-images/our-team/member-2.svg",name: "Michal Kosinski",post: "Community Manager"},
            {class: "member",imgLink: "./aboutus-images/our-team/member-3.svg",name: "Michal Kosinski",post: "Community Manager"},
            {class: "member",imgLink: "./aboutus-images/our-team/member-4.svg",name: "Michal Kosinski",post: "General Manager"},
            {class: "member",imgLink: "./aboutus-images/our-team/member-5.svg",name: "Michal Kosinski",post: "Community Manager"},
            {class: "member",imgLink: "./aboutus-images/our-team/member-6.svg",name: "Michal Kosinski",post: "Community Manager"},
        ],
    },
    // Product Page
    productPage: {
        productTitle: "Network Management Product",
        productName: "NMIS 9",
        productIntro1: "The backbone of your network",
        productIntro2: "management system.",
        productParagraph1: "Network Management Information System",
        productParagraph2: "(NMIS) is the robust software platform",
        productParagraph3: `underpinning Opmantek Performance and`,
        productParagraph4: "Management solutions.",
        productBtn1: "Free Download",
        productBtn2: "Book a Demo",
        productListIntro: "Trusted By over 150,000 Companies including:",
        productCompanyList1 : [
            {imgLink: "./product-images/companies/bloomberg.svg",imgName: "bloomberg"},
            {imgLink: "./product-images/companies/standford.svg",imgName: "stanford"},
            {imgLink: "./product-images/companies/cambridge.svg",imgName: "cambridge"},
            {imgLink: "./product-images/companies/microsoft.svg",imgName: "microsoft"},
            {imgLink: "./product-images/companies/ETh.svg",imgName: "Eth"},
            {imgLink: "./product-images/companies/stitch.svg",imgName: "stitch"},
            {imgLink: "./product-images/companies/google.svg",imgName: "google"},
            {imgLink: "./product-images/companies/opengv.svg",imgName: "opengv"},
            {imgLink: "./product-images/companies/allgero.svg",imgName: "allgero"},
            {imgLink: "./product-images/companies/amazone.svg",imgName: "amazone"},
            {imgLink: "./product-images/companies/circleup.svg",imgName: "circleup"},
            {imgLink: "./product-images/companies/yellowlogo.svg",imgName: "yellowlogo"},
        ],
        productFeatureTitle: "Why Top Companies use NMIS 9",
        product1: [
            {className: "products",imgLink: "./product-images/product-feature/car-engine1.svg",buisnessText:"Sophisticated Business Rules", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
            {className: "products",imgLink: "./product-images/product-feature/think-out-of-the-box1.svg",buisnessText:"Pre-Configured Out-of-the-", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
            {className: "products",imgLink: "./product-images/product-feature/maximize1.svg",buisnessText:"Massively Scalable", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
            {className: "products",imgLink: "./product-images/product-feature/visibility1.svg",buisnessText:"Visible Operational Impact", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
            {className: "products",imgLink: "./product-images/product-feature/heart-monitoring1.svg",buisnessText:"Automated Health Live", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
            {className: "products",imgLink: "./product-images/product-feature/setting1.svg",buisnessText:"Customizable Alert Escalation", buisnessIntro: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sederat nibh tristique ipsum.`},
        ],
        support: "Premium Support",
        supportText1: "Our FirstWave support engineers are highly skilled",
        supportText2: "and experienced in NMIS, Open-AudIT and all of our",
        supportText3: "commercial products and helped customers from",
        supportText4: "Telcos, MSP, enterprise organisations.",
        supportParagraph: "We work closely with you during implementation and rollout, as well as post delivery of our solutions.",
        demoBtn: 'Go to Support',
        supportImgs: [
            {class: "suport-img1",imgLink:"./product-images/support-img1.svg"},
            {class: "suport-img2",imgLink:"./product-images/support-img2.svg"},
        ],
        downloadTitle: "Download NMIS",
        downloadIntro : "NMIS (Network Management Information System) is an open-source network management system that was first released in 1998.",
        downloadLink: "Download dataSheet",
        downloadLabel1: "Download NMIS 9.3.0",
        documentationLink1: "View Documentation",
        downloadLabel2: "Download NMIS 8.8.0",
        documentationLink2: "View Documentation",
        downloadLabel3: "NMIS Source (GitHub)",
        documentationLink3: "View Documentation",
        emailLabel: "email",
        checkboxName: "Apply all Terms and conditions",
        downloadBtn: "Download",
        faq: "FAQ",
        queAns: [
            {class: "faq",text: "What does NMIS stand for?",imgLink: "./product-images/down-arrow.svg"},
            {class: "faq",text: "What does NMIS stand for?",imgLink: "./product-images/down-arrow.svg"},
            {class: "faq",text: "What does NMIS stand for?",imgLink: "./product-images/down-arrow.svg"},
            {class: "faq",text: "What does NMIS stand for?",imgLink: "./product-images/down-arrow.svg"},
            {class: "faq",text: "What does NMIS stand for?",imgLink: "./product-images/down-arrow.svg"},
            {class: "faq",text: "What does NMIS stand for?",imgLink: "./product-images/down-arrow.svg"},
        ],
        downloadTitle2: "Download NMIS",
        downloadIntro2 : "NMIS (Network Management Information System) is an open-source network management system that was first released in 1998.",
        ourSupport: [
            {class: "our-support1",imgLink:"./product-images/support.svg",supportText1: "Community Support",supportText2: "Community Support is also available for all open source users.",joinBtn: "Join"},
            {class: "our-support1",imgLink:"./product-images/github.svg",supportText1: "NMIS on GitHub",supportText2: "Track the NMIS development changes on GitHub.",joinBtn: "Join"},
        ],
    },
    // Blogs Page
    blogPage: {
        blogTitle: "Resource Hub",
        resourseHub: [
            {class: "blogtext",imgLink: "./blog-images/truemark.svg",text1:"Read the latest insights from Opmantek",text2:"engineering about Open-AudIT."},
            {class: "blogtext",imgLink: "./blog-images/truemark.svg",text1:"Network Management Information System",text2:"(NMIS) and the Opmantek suite of products."},
            {class: "blogtext",imgLink: "./blog-images/truemark.svg",text1:"Share your results with potential employers",text2:"to display your strengths and unique fit."},
        ],
        progressNumber: "01/05",
        personalityTitle: "Personality Assessment",
        personalityText: "Understand yourself well with specific insights into your personality and character.",
        viewMoreBtn: "View More",
        blogsTitle: "Blogs",
        blogsBtns: ['Blogs',"Webinars","Enterprise","Prodcasts","White Papers","Case Studies"],
        blogsCards: [
            {class: "all-cards swiper-slide",imgLink: "./blog-images/blog-1.svg",blogTitle:"Reasoning Ability",text1: "Check your reasoning abilities.",text2:"Discover the top traits that help you excel and determine your work fit.",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
            {class: "all-cards swiper-slide",imgLink: "./blog-images/blog-2.svg",blogTitle:"Personality Assessment",text1: "Discover the top traits that help you excel and determine your work fit.",text2:"Check your reasoning abilities.",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
            {class: "all-cards swiper-slide",imgLink: "./blog-images/blog-3.svg",blogTitle:"Cope Inventory",text1: "Discover the top traits that help you excel and determine your work fit.",text2:"Check your reasoning abilities.",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
            {class: "all-cards swiper-slide",imgLink: "./blog-images/blog-4.png",blogTitle:"Entrepreneurial Personality",text2:"Get a clean picture of yourself with insights into your personality and character.</p>",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
        ],
        viewAll: "View All",
    },
    postPage: {
        postTitle1: 'Using Configuration',
        postTitle2: 'Management to',
        postTitle3: 'Detect Unwanted',
        postTitle4: 'Software',
        postParagraph1: "Lorem Ipsum do eiusmod tempor incididunt ut",
        postParagraph2: "labore et dolore magnaaliqua. Ut enim ad minim nostrud",
        postParagraph3: "exercitation ullamcolaboris nisi ut aliquip ex ea commodo",
        postParagraph4: "consequat.",
        postMsg: "by Emily Coe",
        ansQueTitle1: "Is the Log4Shell or Log4J vulnerability an issue for Opmantek?",
        ansQueTitle2: "What is the Log4Shell Vulnerability?",
        ansQueTitle3: "What is Apache Log4J?",
        ansQueTitle4: "How can Opmantek help you find computers that are using Log4J?",
        ansQueParagraph1:"No. Opmantek products do not use Java or Log4J, see more details here:",
        link1: "Opmantek",
        link2: "Products and Apache Log4J Vulnerability.",
        ansQueParagraph2: "The Log4Shell is a zero-day vulnerability in Log4J, which allows attackers to execute",
        ansQueParagraph3: "arbitrary Java code on the remote computers, including accessing sensitive",
        ansQueParagraph4: "information.  The CVSS score is 10, the highest possible score.  You can read more",
        ansQueParagraph5: "details here:",
        link3: "Log4Shell – Wikipedia.",
        ansQueParagraph6: "Apache Log4J is a popular libr/ary used by many products written in Java.  It provides a ",
        ansQueParagraph7: "consistent way for applications to log messages including information, debug, errors,",
        ansQueParagraph8: "etc.  It has become the primary way Java applications do logging and is widely used.",
        ansQueParagraph9: "Log4J is a Java libr/ary which means that there are files installed onto the computer",
        ansQueParagraph10: "which Java loads when it runs the program.  You can search for these files using Linux",
        ansQueParagraph11: "commands and determine if the files exist on the server.",
        subscribeTitle: "Stay up to Date",
        emailLabel: "Email",
        subscribeBtn: 'Subscribe',
        blogsTitle: "Blogs",
        blogsBtns: ['Blogs',"Webinars","Enterprise","Prodcasts","White Papers","Case Studies"],
        blogsCards: [
            {class: "all-cards",imgLink: "./blog-images/blog-1.svg",blogTitle:"Reasoning Ability",text1: "Check your reasoning abilities.",text2:"Discover the top traits that help you excel and determine your work fit.",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
            {class: "all-cards",imgLink: "./blog-images/blog-2.svg",blogTitle:"Personality Assessment",text1: "Discover the top traits that help you excel and determine your work fit.",text2:"Check your reasoning abilities.",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
            {class: "all-cards",imgLink: "./blog-images/blog-3.svg",blogTitle:"Cope Inventory",text1: "Discover the top traits that help you excel and determine your work fit.",text2:"Check your reasoning abilities.",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
            {class: "all-cards",imgLink: "./blog-images/blog-4.png",blogTitle:"Entrepreneurial Personality",text2:"Get a clean picture of yourself with insights into your personality and character.</p>",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
        ],
    },
    // Legal Page
    LegalPage: {
        title: "legal terms",
        legalText1: "Opmantek prides itself on providing users",
        legalText2: "access to all their data.",
        paragraph1: "This begins with our products giving you all",
        paragraph2: "the data on your network, but it extends to",
        paragraph3: "any of your personal information. We pride",
        paragraph4: "ourself on ensuring this is safe.",
        downloadBtn: "Downlode all PDF",
        legalterms1: [
            {class:"process-list",imgLink: "./legal-terms-imgs/legal-process/privacy.svg",title:"Privacy Statement",text1: "About this Privacy Statement, Opmantek is the like th",text2: "committed to maintaining the security of…",downloadLink: "Download PDF"},
            {class:"process-list",imgLink: "./legal-terms-imgs/legal-process/nda.svg",title:"NDA - Confidentiality Agreement",text1: "Party and Counterparty have agreed to make",text2: "available Confidential…",downloadLink: "Download PDF"},
            {class:"process-list",imgLink: "./legal-terms-imgs/legal-process/eula.svg",title:"EULA - End User License Agreement",text1: "Subject to the terms and conditions of this",text2: "Agreement, Licensor hereby…",downloadLink: "Download PDF"},
            {class:"process-list",imgLink: "./legal-terms-imgs/legal-process/cookie.svg",title:"Cookie Policy",text1: "We use technologies and third-party services that",text2: "use Google Analytics, pixels, tags and web ...",downloadLink: "Download PDF"},
            {class:"process-list",imgLink: "./legal-terms-imgs/legal-process/trust.svg",title:"Trust & Data Processing",text1: "Opmantek prides itself on getting all our users access",text2: "to all their data. This…",downloadLink: "Download PDF"},
            {class:"process-list",imgLink: "./legal-terms-imgs/legal-process/tos.svg",title:"ToS - Terms of Service",text1: "Access and Use License. Subject to the terms and",text2: "conditions of this Agreement…",downloadLink: "Download PDF"},
            {class:"process-list",imgLink: "./legal-terms-imgs/legal-process/licence.svg",title:"Licensing",text1: "The purpose of this licensing page is to list the items",text2: "products and licenses included in Opmantek ...",downloadLink: "Download PDF"},
            {class:"process-list",imgLink: "./legal-terms-imgs/legal-process/privacy-statment.svg",title:"Privacy Request",text1: "We are committed to ensuring that the data you",text2: "provide to us is secure. Reach out to use any time...",downloadLink: "Download PDF"},
        ],
    },
    // Home Page
    homePage: {
        homeTitle1: "Maximize Your IT",
        homeTitle2: "Investment",
        homeText1: "We will help you to audit, manage,",
        homeText2: "automate and secure your entire business.",
        homeText3: 'a demo with our specialists.',
        homeLabel1: "Cybersecurity",
        homeLabel2: "Network Management",
        demoBtn: "Book a Demo",
        companyListIntro: "Trusted By over 150,000 Companies including:",
        companyList1 : [
            {imgLink: "./images/bloomberg.svg",imgName: "bloomberg"},
            {imgLink: "./images/standford.svg",imgName: "stanford"},
            {imgLink: "./images/cambridge.svg",imgName: "cambridge"},
            {imgLink: "./images/microsoft.svg",imgName: "microsoft"},
            {imgLink: "./images/ETh.svg",imgName: "Eth"},
            {imgLink: "./images/stitch.svg",imgName: "stitch"},
            {imgLink: "./images/google.svg",imgName: "google"},
            {imgLink: "./images/opengv.svg",imgName: "opengv"},
            {imgLink: "./images/allgero.svg",imgName: "allgero"},
            {imgLink: "./images/amazone.svg",imgName: "amazone"},
            {imgLink: "./images/circleup.svg",imgName: "circleup"},
            {imgLink: "./images/yellowlogo.svg",imgName: "yellowlogo"},
        ],
        homeAboutText1: "FRACTION OF A COST",
        homeAboutTitle: "Premium Network Management",
        btns: ["Service Providers","MSP","Enterprise","SMS"],
        paragraph1: "The whole is greater than the sum of the parts.Opmantek offers MSP Software that is designed",
        paragraph2: "to scale.",
        paragraph3: "To quickly start my startup landing page design, I was looking for a landing page UI Kit. Landify is one of the best landing page UI kit I have come across. It’s so flexible, well organised and easily editable.To quickly start my startup landing page design, I was looking for a landing page UI Kit. Landify is one of the best landing page UI kit I have come across. It’s so flexible, well organised and easily editable.",
        cards : [
            {class: "card1",imgLink: "./images/card-1.svg",text: "Get one step closer to self-improvement and personal growth by learning more about yourself"},
            {class: "card1",imgLink: "./images/card-2.svg",text: "Improve your entrepreneurial skills by discovering your business personality traits"},
            {class: "card1",imgLink: "./images/card-3.svg",text: "Share your entrepreneurial personality test results with your friends and see how you all compare"},
        ],
        programmeTitle: "Machine Learning Powered, Multi-tenant",
        programmeName: "Cybersecurity Platform",
        programmeText1: "Use our machine learning powered propriotory solutions",
        programmeText2: "to protect your business from any cybersecurity attacts.",
        programmeText3: "Schedule a demo with our friendly experts.",
        featureTitle1: "Plug-n-play configuration",
        featureText1: "Secure your organization without changing all",
        featureText2: "the settings",
        featureTitle2: "Easy Integration",
        featureText3: "Smooth Integrated with Microsoft Office 365",
        btn: "Schedule a demo",
        programmeCards1: [
            {class: "programcard1",imgLink: "./images/feature3.svg",title: "Web Security",text1: "Lorem ipsum dolor sit amet, consectetur adipiscing",text2: "elit. Mattis et sed nam sem telluserat." },
            {class: "programcard2",imgLink: "./images/feature4.svg",title: "Email Security",text1: "Lorem ipsum dolor sit amet, consectetur adipiscing",text2: "elit. Mattis et sed nam sem telluserat." },
            {class: "programcard3",imgLink: "./images/feature5.svg",title: "Endpoint Security",text1: "Lorem ipsum dolor sit amet, consectetur adipiscing",text2: "elit. Mattis et sed nam sem telluserat." },
            {class: "programcard4",imgLink: "./images/feature6.svg",title: "Web Security",text1: "Lorem ipsum dolor sit amet, consectetur adipiscing",text2: "elit. Mattis et sed nam sem telluserat." },
        ],
        decisionTitle: "Need Help Making a Decision?",
        desicisions: [
            {class: "dicision-1",imgLink: "./images/Icon.png",text: "See the changes you can make by using automated features that matters to you"},
            {class: "dicision-1",imgLink: "./images/Icon.png",text: "Learn how FirstWave technology can be customised for your business needs"},
            {class: "dicision-1",imgLink: "./images/Icon.png",text: "Get Top notch support from our cybersecurity & infrastructure management experts"},
        ],
        testimonialTitel1: "Real stories from",
        testimonialTitel2: "Real Customers",
        inspireText: "Get inspired by these stories.",
        testimonialcard1Texts: "To quickly start my startup landing page design, I was looking for a landing page UI Kit. Landify is one of the best landing page UI kit I have come across. It’s so flexible, well organised and easily editable.",
        testimonialcard1Name: "Floyd Miles",
        testimonialcard1Post: "Vice President, GoPro",
        testimonialcard2Texts: "I used landify and created a landing page for my startup within a week. The Landify UI Kit is simple and highly intuitive, so anyone can use it.",
        testimonialcard2Name: "Jane Cooper",
        testimonialcard2Post: "CEO, Airbnb",
        testimonialcard3Texts: "Landify saved our time in designing my company page.",
        testimonialcard3Name: "Kristin Watson",
        testimonialcard3Post: "Co-Founder, BookMyShow",
    },
    companyLeaderShipPage: {
        manager: "Manager",
        managerDescription: "Michal Kosinski is an Associate Professor in Organizational Behavior at Stanford’s Graduate School of Business and studies job-person fit and humans using cutting-edge computational methods.",
        link: "Read More...",
        socialIcons : [
            {imgLink: "./company-leadership/fb.svg" ,imgName: "icons"},
            {imgLink: "./company-leadership/tw.svg" ,imgName: "icons"},
            {imgLink: "./company-leadership/ln.svg" ,imgName: "icons"},
            {imgLink: "./company-leadership/ig.svg" ,imgName: "icons"},
        ],
        paragraph1: "Our FirstWave support engineers are highly skilled and experienced in NMIS, Open-AudIT and all of our commercial products and helped customers from Telcos, MSP, enterprise organisations.Our FirstWave support engineers are highly skilled and experienced in NMIS, Open-AudIT and all of our commercial products and helped customers from Telcos, MSP, enterprise organisations..",
        paragraph2: "Our FirstWave support engineers are highly skilled and experienced in NMIS, Open-AudIT and all of our commercial products and helped customers from Telcos, MSP, enterprise organisations.",
        paragraph3: "Our FirstWave support engineers are highly skilled and experienced in NMIS, Open-AudIT and all of our commercial products and helped customers from Telcos, MSP, enterprise organisations.Our FirstWave support engineers are highly skilled and experienced in NMIS, Open-AudIT and all of our commercial products and helped customers from Telcos, MSP, enterprise organisations.Our FirstWave support engineers are highly skilled and experienced in NMIS, Open-AudIT and all of our commercial products and helped customers from Telcos, MSP, enterprise organisations.",
        quotesMsg: "Quotes",
        msgText1: "We had an incredible experience working with Landify and were",
        msgText2: "impressed they made such a big difference in only three weeks. Our",
        msgText3: "team is so grateful for the wonderful improvements they made and their",
        msgText4: "ability to get familiar with the product concept so quickly. It acted as a",
        msgText5: "catalyst to take our design to the next level and get more eyes on our",
        msgText6: "product.",
        managerName: "Scarlett Johansson",
        post: "Manager",
    },
    latestNewsPage: {
        title: 'Latest news',
        link: "see all news",
        news: [
            {class: "news",imgLink: "./latest-news-images/news1.svg",name1: "Michal Kosinski is an Associate",name2:"Professor in Organizational.",intro: "We’re a team made up of individuals, with unconventional career paths military ...",link: "Read More..."},
            {class: "news",imgLink: "./latest-news-images/news2.svg",name1: "Michal Kosinski is an Associate",name2:"Professor in Organizational.",intro: "We’re a team made up of individuals, with unconventional career paths military ...",link: "Read More..."},
        ],
        blogsTitle: "Blogs",
        blogsBtns: ['Blogs',"Webinars","Enterprise","Prodcasts","White Papers","Case Studies"],
        blogsCards: [
            {class: "all-cards",imgLink: "./blog-images/blog-1.svg",blogTitle:"Reasoning Ability",text1: "Check your reasoning abilities.",text2:"Discover the top traits that help you excel and determine your work fit.",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
            {class: "all-cards",imgLink: "./blog-images/blog-2.svg",blogTitle:"Personality Assessment",text1: "Discover the top traits that help you excel and determine your work fit.",text2:"Check your reasoning abilities.",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
            {class: "all-cards",imgLink: "./blog-images/blog-3.svg",blogTitle:"Cope Inventory",text1: "Discover the top traits that help you excel and determine your work fit.",text2:"Check your reasoning abilities.",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
            {class: "all-cards",imgLink: "./blog-images/blog-4.png",blogTitle:"Entrepreneurial Personality",text2:"Get a clean picture of yourself with insights into your personality and character.</p>",btn: "Read More",imgClass:"readmore",imgLink2: "./blog-images/readmore.svg",time:"30 Min"},
        ],
    },
    financialPage: {
        title: "Financial Reporting",
        text1: " Opmantek prides itself on providing users ",
        text2: "access to all their data.",
        text3: "This begins with our products giving you all",
        text4: "the data on your network, but it extends to",
        text5: "any of your personal information. We pride",
        text6: "ourself on ensuring this is safe.",
        annualReportsTitle: "Annual Reports",
        reports1: [
            {class: "yearly",year: "2021",link: "Download Report"},
            {class: "yearly",year: "2021",link: "Download Report"},
            {class: "yearly",year: "2021",link: "Download Report"},
        ],
        reports2: [
            {class: "yearly",year: "2021",link: "Download Report"},
            {class: "yearly",year: "2021",link: "Download Report"},
            {class: "yearly",year: "2021",link: "Download Report"},
        ],
        corporateTitle: "Corporate Governance",
        paragraphtext1: "The Board of FirstWave Cloud Technology Limited has been established to provide a blend ofqualifications, skills",
        paragraphtext2: "and experience required to manage a company in a cloud-based technology environment. The Company’s aim",
        paragraphtext3: "in determining Board membership is to create a balanced and informed group to assist the Company in making",
        paragraphtext4: "decisions relating to all corporate and governance related matters. The Board’s primary responsibility is to the",
        paragraphtext5: "shareholders as owners of the Company. In recognition of its duty, it recognizes an important obligation to act in",
        paragraphtext6: "the best interests of the Company, act honestly, exercise care and due diligence and support a corporate",
        paragraphtext7: "governance initiative that fosters integrity." ,
        paragraphtext8: "The Board seeks to ensure that the Company is properly managed to protect and enhance shareholder interests,",
        paragraphtext9: "and that the Company, its Directors, officers and personnel operate in an appropriate environment of good",
        paragraphtext10: "corporate governance. Accordingly, the Board has created a framework for managing the Company, including",
        paragraphtext11: "adopting relevant internal controls, risk management processes and corporate governance policies and",
        paragraphtext12: "practices which it believes are appropriate for the Company’s business and which are designed to promote the",
        paragraphtext13: "responsible management and conduct of the Company.",
        copyText1: "Copies of the Company’s key corporate governance policies and charters for the Board and each of its",
        copyText2: "committees are available below.",
        policyTitle: "Corporate Governance Policies - (click on name to download)",
        policies: [
            {class:"policy-download",label: "Appendix 4G and Corporate Governance"},
            {class:"policy-download",label: "FCT Audit and Risk Committee Charter"},
            {class:"policy-download",label: "FCT Board Charter"},
            {class:"policy-download",label: "FCT Board Charter"},
            {class:"policy-download",label: "FCT Code of Conduct"},
            {class:"policy-download",label: "FCT Remuneration and Nomination Committee"},
            {class:"policy-download",label: "FCT Securities Trading Policy"},
            {class:"policy-download",label: "FCT Constitution"},
            {class:"policy-download",label: "FCT Privacy Statement"},
            {class:"policy-download",label: "FCT Anti-Bribery and Corruption Policy"},
            {class:"policy-download",label: "FCT Whistleblower Policy"},
        ],
        faqTitle: "Frequently asked questions",
        queAns: [
            {class: "que-ans",text: "What is the ASX ticker code for FirstWave Cloud Technology Limited?",imgLink: "./financial-images/expand_more.svg"},
            {class: "que-ans",text: "What was the IPO price and issue date of FirstWave’s shares?",imgLink: "./financial-images/expand_more.svg"},
            {class: "que-ans",text: "How do I make changes to my holding?",imgLink: "./financial-images/expand_more.svg"},
            {class: "que-ans",text: "Where will I find FirstWave’s Corporate Governance Statement?",imgLink: "./financial-images/expand_more.svg"},
            {class: "que-ans",text: "What is the ASX ticker code for FirstWave Cloud Technology Limited?",imgLink: "./financial-images/expand_more.svg"},
            {class: "que-ans",text: "What is the ASX ticker code for FirstWave Cloud Technology Limited?",imgLink: "./financial-images/expand_more.svg"},
        ],
    },
    footer: {
        footerTitle1: "Lorem ipsum dolor sit amet,",
        footerTitle2: "consectetur adipiscing elit. Morbi non",
        footerTitle3: "leo at justo posuere luctus. Maecenas",
        footerTitle4: "id mauris sit.",
        icons: [
            {mainClass: "social-icon",imgClass: "fb-icon",imgLink: './images/fb.svg'},
            {mainClass: "social-icon",imgClass: "tw-icon",imgLink: './images/twitter.svg'},
            {mainClass: "social-icon",imgClass: "linkdin-icon",imgLink: './images/linkdin.svg'},
            {mainClass: "social-icon",imgClass: "instagram-icon",imgLink: './images/instagram.svg'},
        ],
        opmentechTitle: "Opmentek",
        demoLink: "Get Demo",
        downloadLink: "Download",
        productTitle: "Products",
        productList: ["NMIS","Open-AudiT","opEvents","opConfig","opHa"],
        resourceTitle: "Resources",
        resorceLinks: ['Blog',"Webinars","Opmentek Wiki","Prices","Contact Us"],
        contactTitle: "Reach Us",
        supportTitle: "Support:",
        mail: "hello@landify.co",
        numberText: "General:",
        number: "+91 98765 43210",
        officeAddressTitle1: "USA Office:",
        officeAddressText1: "772 Lyonwood Ave",
        officeAddressText2: "Walnut, CA 91789",
        officeAddressTitle2: "Australia Office:",
        rights: "Opmantek 2022. All rights reserved",
        policy: "Terms & Privacy",
    },
    header: {
        hederLinksName: [
            {navLink: "product",navName: "Product"},
            {navLink: "blog",navName: "blogs"},
            {navLink: "post",navName: "Posts"},
            {navLink: "about",navName: "About Us"},
            {navLink: "legal",navName: "Legal Terms"},
            {navLink: "signin",navName: "signin"},
        ]
    }

}


export default data;